# Smart Supply Chain Disruption & Delivery Risk Predictor

## 2. Data Cleaning & Preparation

In this section, we clean and prepare the dataset for further analysis and machine learning by handling missing values, removing unusable and redundant columns, correcting data inconsistencies, converting data types, checking numerical anomalies, and removing potential data leakage.

In [201]:
import numpy as np 
import pandas as pd

In [202]:
data = pd.read_csv("D:/projects/supply chain project/datasets/raw/DataCoSupplyChainDataset.csv",encoding='latin1')

In [203]:
data.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [204]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [205]:
#drop leakage columns and unusable columns
data = data.drop(columns=['Customer Password','Customer Email','Customer Fname',
                   'Customer Lname','Product Description','Product Image',
                   'Product Status','Order Id','Order Customer Id',
                   'Days for shipping (real)','Delivery Status','shipping date (DateOrders)',
                   'Order Status','Benefit per order','Order Item Profit Ratio',
                   'Order Profit Per Order'])

In [206]:
data.shape

(180519, 37)

In [207]:
#checking missing values
data.isnull().sum()

Type                                  0
Days for shipment (scheduled)         0
Sales per customer                    0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
order date (DateOrders)               0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Region                          0
Order State                           0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Name                          0
Product Price                         0
Shipping Mode                         0
dtype: int64

In [208]:
#missing of order zipcode based on order country
missing_by_country = data.groupby('Order Country')['Order Zipcode'].apply(
    lambda x: x.isna().mean() * 100
)

missing_by_country.describe()

count    164.000000
mean      99.390244
std        7.808688
min        0.000000
25%      100.000000
50%      100.000000
75%      100.000000
max      100.000000
Name: Order Zipcode, dtype: float64

In [209]:
#drop order zipcode column
data = data.drop(columns=['Order Zipcode'])

In [210]:
data.shape

(180519, 36)

In [211]:
#find the 3 missing customer zipcode column and understand how it is assosiate with other columns
data.loc[
    data['Customer Zipcode'].isna(),
    ['Customer City', 'Customer State', 'Customer Country', 'Customer Zipcode']
]

      Customer City Customer State Customer Country  Customer Zipcode
35704            CA          95758          EE. UU.               NaN
46440            CA          95758          EE. UU.               NaN
82511            CA          91732          EE. UU.               NaN

In [212]:
#finding number of unique values in customer info columns
data[['Customer Zipcode',"Customer City","Customer State",'Customer Country']].nunique()

Customer Zipcode    995
Customer City       563
Customer State       46
Customer Country      2
dtype: int64

In [213]:
#convert order date columns from object dtype to datetime dtype
data['order date (DateOrders)'] = pd.to_datetime(data['order date (DateOrders)'])

In [214]:
#understanding unique values from differnet columns
print("Type column unique values : ", data['Type'].unique())
print("\n\ncustomer segment column unique values : ",data['Customer Segment'].unique())
print("\nMarket column unique values : ",data['Market'].unique())
print("\nShipping mode column unique values : ",data['Shipping Mode'].unique())
print("\nDepartment name column unique values : ",data['Department Name'].unique())
print("\nCategory Name column unique values : ", data['Category Name'].unique())
print("\nCustomer City column unique values : ", data['Customer City'].unique())
print("\nCustomer Country column unique values : ", data['Customer Country'].unique())
print("\nCustomer State column unique values : ", data['Customer State'].unique())
print("\nCustomer Street column unique values : ", data['Customer Street'].unique())
print("\nOrder City column unique values : ", data['Order City'].unique())
print("\nOrder Country column unique values : ", data['Order Country'].unique())
print("\nOrder Region column unique values : ", data['Order Region'].unique())
print("\nOrder State column unique values : ", data['Order State'].unique())
print("\nProduct Name column unique values : ", data['Product Name'].unique())

Type column unique values :  ['DEBIT' 'TRANSFER' 'CASH' 'PAYMENT']


customer segment column unique values :  ['Consumer' 'Home Office' 'Corporate']

Market column unique values :  ['Pacific Asia' 'USCA' 'Africa' 'Europe' 'LATAM']

Shipping mode column unique values :  ['Standard Class' 'First Class' 'Second Class' 'Same Day']

Department name column unique values :  ['Fitness' 'Apparel' 'Golf' 'Footwear' 'Outdoors' 'Fan Shop' 'Technology'
 'Book Shop' 'Discs Shop' 'Pet Shop' 'Health and Beauty ']

Category Name column unique values :  ['Sporting Goods' 'Cleats' 'Shop By Sport' "Women's Apparel" 'Electronics'
 'Boxing & MMA' 'Cardio Equipment' 'Trade-In' "Kids' Golf Clubs"
 'Hunting & Shooting' 'Baseball & Softball' "Men's Footwear"
 'Camping & Hiking' 'Consumer Electronics' 'Cameras ' 'Computers'
 'Basketball' 'Soccer' "Girls' Apparel" 'Accessories' "Women's Clothing"
 'Crafts' "Men's Clothing" 'Tennis & Racquet' 'Fitness Accessories'
 'As Seen on  TV!' 'Golf Balls' 'Strength Training' "Children's Clothing"
 'Lacrosse' 'Baby ' 'Fishing' 'Books ' 'DVDs' 'CDs ' 'Garden' 'Hockey'
 'Pet Supplies' 'Health and Beauty' 'Music' 'Video Games' 'Golf Gloves'
 'Golf Bags & Carts' 'Golf Shoes' 'Golf Apparel' "Women's Golf Clubs"
 "Men's Golf Clubs" 'Toys' 'Water Sports' 'Indoor/Outdoor Games']

Customer City column unique values :  ['Caguas' 'San Jose' 'Los Angeles' 'Tonawanda' 'Miami' 'San Ramon'
 'Freeport' 'Salinas' 'Peabody' 'Canovanas' 'Paramount' 'Mount Prospect'
 'Long Beach' 'Rancho Cordova' 'Billings' 'Wilkes Barre' 'Roseville'
 'Bellflower' 'Wheaton' 'Detroit' 'Dallas' 'Carlisle' 'Newark'
 'Panorama City' 'Atlanta' 'Fremont' 'Rochester' 'Bayamon' 'Guayama'
 'Juana Diaz' 'Fort Washington' 'Bakersfield' 'Corona' 'Cincinnati'
 'Germantown' 'Carrollton' 'Houston' 'Ewa Beach' 'Lakewood' 'Rome' 'Vista'
 'Fort Worth' 'Fond Du Lac' 'Philadelphia' 'Ontario' 'Oviedo' 'Buffalo'
 'Honolulu' 'Oceanside' 'North Tonawanda' 'Clovis' 'Jamaica'
 'Granite City' 'Medford' 'Pomona' 'Tempe' 'Santa Ana' 'York' 'Aurora'
 'Simi Valley' 'Silver Spring' 'Saint Paul' 'San Antonio' 'Bronx'
 'Greenville' 'Morristown' 'San Diego' 'Oxnard' 'Albuquerque' 'Amarillo'
 'Lutz' 'Bend' 'East Brunswick' 'Lancaster' 'Hampton' 'New York'
 'Porterville' 'Portland' 'Strongsville' 'El Paso' 'Del Rio' 'Bountiful'
 'Kent' 'Chicago' 'Plymouth' 'Far Rockaway' 'Garden Grove' 'Placentia'
 'Mentor' 'Santa Clara' 'Union' 'Westminster' 'Pompano Beach' 'Azusa'
 'Fort Lauderdale' 'Princeton' 'Perth Amboy' 'Loveland' 'Virginia Beach'
 'Louisville' 'Lockport' 'Staten Island' 'Tucson' 'Cleveland' 'Webster'
 'Stockton' 'Martinsburg' 'Cumberland' 'Pekin' 'Tallahassee'
 'Jacksonville' 'Woonsocket' 'Lithonia' 'Oak Lawn' 'Alhambra' 'New Haven'
 'Phoenix' 'Kenner' 'Washington' 'Holland' 'Morrisville' 'Memphis'
 'Federal Way' 'West Covina' 'Ventura' 'Valrico' 'Kaneohe' 'Brooklyn'
 'Lodi' 'Murfreesboro' 'Carlsbad' 'Hamilton' 'Hayward' 'Bridgeton'
 'Bay Shore' 'Palatine' 'Smyrna' 'Van Nuys' 'Opa Locka' 'Edison' 'Baytown'
 'Sylmar' 'Burnsville' 'Huntington Station' 'Sunnyvale' 'Sugar Land'
 'Brighton' 'Bismarck' 'Gaithersburg' 'Lilburn' 'Provo' 'Columbia'
 'Marietta' 'Rio Grande' 'Denver' 'Taylor' 'Saint Charles' 'Cupertino'
 'Springfield' 'Mission Viejo' 'Roswell' 'Ypsilanti' 'Peoria' 'Clementon'
 'Antioch' 'Salt Lake City' 'Granada Hills' 'Hempstead' 'Astoria' 'Gilroy'
 'Lenoir' 'Columbus' 'Albany' 'Humacao' 'Lindenhurst' 'Elyria' 'Riverside'
 'Carson' 'Mesa' 'San Juan' 'Vega Baja' 'Mayaguez' 'Arecibo'
 'San Sebastian' 'Eugene' 'Algonquin' 'Indianapolis' 'Buena Park'
 'Catonsville' 'Jersey City' 'Lombard' 'New Bedford' 'Newburgh' 'Lansdale'
 'Baltimore' 'Fullerton' 'Sacramento' 'Greensboro' 'Roseburg' 'Modesto'
 'Encinitas' 'Watsonville' 'Meridian' 'Endicott' 'Katy' 'Visalia' 'Lompoc'
 'Ogden' 'Raleigh' 'Hacienda Heights' 'Union City' 'Hollywood'
 'Bolingbrook' 'West Lafayette' 'Woodbridge' 'Weslaco' 'Bell Gardens'
 'La Mirada' 'North Bergen' 'Madison' 'South San Francisco'
 'North Las Vegas' 'Methuen' 'Costa Mesa' 'Glen Burnie' 'Fairfield'
 'Winnetka' 'Mcallen' 'Joliet' 'Brownsville' 'Pawtucket'
 'Colorado Springs' 'Quincy' 'Pittsfield' 'Chino' 'Marion' 'North Hills'
 'Salina' 'Hyattsville' 'North Richland Hills' 'Spring Valley' 'Lawrence'
 'Milpitas' 'Rowland Heights' 'Gardena' 'Cicero' 'Asheboro' 'La Crosse'
 'Florissant' 'Canyon Country' 'Ithaca' 'Allentown' 'Escondido' 'Martinez'
 'Troy' 'Arlington' 'Davis' 'Chandler' 'Elgin' 'Palmdale' 'Massapequa'
 'Pittsburg' 'West New York' 'Orlando' 'Hanover' 'Glendale' 'Enfield'
 'Baldwin Park' 'Chino Hills' 'Toms River' 'Wyandotte' 'Mililani' 'Harvey'
 'Mechanicsburg' 'Opelousas' 'Kailua' 'Norfolk' 'Elmhurst' 'Chillicothe'
 'Canoga Park' 'Jackson' 'Moreno Valley' 'New Orleans' 'San Benito'
 'New Castle' 'Bloomfield' 'Cypress' 'Marrero' 'Grand Prairie' 'Greeley'
 'Littleton' 'Longmont' 'Chesapeake' 'Englewood' 'Arlington Heights'
 'Tampa' 'Irvington' 'Forest Hills' 'Dearborn' 'Compton' 'Garland'
 'Waipahu' 'Carmichael' 'Tustin' 'Anaheim' 'Canton' 'Stafford'
 'South Richmond Hill' 'Middletown' 'West Orange' 'Daly City'
 'Powder Springs' 'Parkville' 'Hialeah' 'Beloit' 'Aguadilla' 'Carolina'
 'Yauco' 'Saint Peters' 'Augusta' 'Chapel Hill' 'East Lansing' 'Stamford'
 'Diamond Bar' 'Milwaukee' 'Lawrenceville' 'Manchester' 'La Puente'
 'Victorville' 'Richmond' 'Eagle Pass' 'Fontana' 'Ballwin' 'New Braunfels'
 'Las Vegas' 'Goose Creek' 'Pharr' 'Yonkers' 'El Monte' 'Reynoldsburg'
 'Hamtramck' 'Medina' 'Highland' 'Jonesboro' 'Elk Grove' 'Montebello'
 'San Francisco' 'Glenview' 'Rock Hill' 'Austin' 'Scottsdale' 'Santa Cruz'
 'Oregon City' 'Annandale' 'Plano' 'Piscataway' 'El Cajon' 'Hilliard'
 'Orange Park' 'Decatur' 'San Pablo' 'Douglasville' 'Henderson'
 'College Station' 'Round Rock' 'Mesquite' 'Broken Arrow' 'Redmond'
 'Findlay' 'La Habra' 'Laguna Hills' 'San Bernardino' 'Apex'
 'South El Monte' 'Irving' 'Blacksburg' 'Dorchester Center' 'Potomac'
 'Winter Park' 'Stone Mountain' 'Goleta' 'Hagerstown' 'Alameda'
 'Saint Louis' 'Pico Rivera' 'Chula Vista' 'Hollister' 'North Hollywood'
 'New Brunswick' 'Beaverton' 'Chicago Heights' 'Hesperia' 'Cary' 'Sanford'
 'Laredo' 'Westland' 'Stockbridge' 'Carol Stream' 'Wichita' 'Olathe'
 'Flushing' 'Lynwood' 'Revere' 'Westerville' 'Cordova' 'Hanford' 'Rialto'
 'Mchenry' 'Mission' 'Salem' 'Duluth' 'Danbury' 'Frankfort' 'Upland'
 'Rosemead' 'Mount Pleasant' 'Lake Forest' 'West Chester' 'Woodside'
 'Norcross' 'Fresno' 'Zanesville' 'Painesville' 'Lynnwood' 'Massillon'
 'Crystal Lake' 'Rego Park' 'Ann Arbor' 'Wyoming' 'La Mesa' 'Edinburg'
 'Howell' 'Michigan City' 'Sheboygan' 'Moline' 'Yuma' 'Campbell'
 'Charlotte' 'Oakland' 'San Marcos' 'Walnut' 'Harlingen' 'Rio Rancho'
 'Nashville' 'Annapolis' 'Laguna Niguel' 'Santee' 'West Jordan' 'Hickory'
 'Manati' 'Trujillo Alto' 'Ponce' 'Toa Alta' 'Irwin' 'South Ozone Park'
 'Ridgewood' 'Bowling Green' 'Richardson' 'Sun Valley' 'Huntington Beach'
 'Fargo' 'Waukegan' 'Highland Park' 'Cerritos' 'Lewisville' 'Alpharetta'
 'New Albany' 'Denton' 'Temecula' 'Tinley Park' 'Dundalk' 'Crown Point'
 'Lawton' 'Fayetteville' 'Milford' 'Bartlett' 'Reno' 'Passaic' 'Reseda'
 'Levittown' 'Wayne' 'Metairie' 'Wheeling' 'Hawthorne' 'Napa' 'Berwyn'
 'Fountain Valley' 'Las Cruces' 'Apopka' 'Folsom' 'El Centro'
 'Jackson Heights' 'Pacoima' 'Hendersonville' 'Clearfield' 'Seattle'
 'Saginaw' 'Conway' 'Sandusky' 'San Pedro' 'Grove City' 'Knoxville'
 'Huntington Park' 'Greensburg' 'Poway' 'O Fallon' 'Chambersburg' 'Normal'
 'Lynn' 'Bensalem' 'Bristol' 'Williamsport' 'Longview' 'Norwalk' 'Bayonne'
 'Tulare' 'National City' 'Dayton' 'Tracy' 'Summerville' 'Merced'
 'Brockton' 'Vallejo' 'West Haven' 'Pasadena' 'South Gate' 'Warren'
 'Clarksville' 'Muskegon' 'Brandon' 'Rancho Cucamonga' 'Santa Maria'
 'Doylestown' 'Colton' 'Indio' 'Plainfield' 'Bellingham' 'Spring'
 'Livermore' 'Santa Fe' 'Palo Alto' 'Henrico' 'Des Plaines' 'Birmingham'
 'Broomfield' 'Guaynabo' 'Cayey' 'Citrus Heights' 'Spokane' 'Dubuque'
 'Madera' 'Everett' 'Brentwood' 'Morganton' 'Vacaville' 'Malden'
 'Gwynn Oak' 'Toa Baja' 'Taunton' 'Freehold' 'Sumner' 'Wilmington' 'CA']

Customer Country column unique values :  ['Puerto Rico' 'EE. UU.']

Customer State column unique values :  ['PR' 'CA' 'NY' 'FL' 'MA' 'IL' 'MT' 'PA' 'MI' 'TX' 'DE' 'GA' 'MD' 'OH'
 'HI' 'NJ' 'WI' 'AZ' 'CO' 'MN' 'NC' 'NM' 'OR' 'SC' 'VA' 'UT' 'WA' 'KY'
 'WV' 'RI' 'CT' 'LA' 'TN' 'DC' 'ND' 'MO' 'IN' 'ID' 'NV' 'KS' 'AR' 'OK'
 'AL' 'IA' '95758' '91732']

Customer Street column unique values :  ['5365 Noble Nectar Island' '2679 Rustic Loop' '8510 Round Bear Gate' ...
 '245 Lost Way ' '2455 Merry Hollow ' '8621 Broad Forest ']

Order City column unique values :  ['Bekasi' 'Bikaner' 'Townsville' ... 'Tongling' 'Liuyang' 'Nashua']

Order Country column unique values :  ['Indonesia' 'India' 'Australia' 'China' 'Japón' 'Corea del Sur'
 'Singapur' 'Turquía' 'Mongolia' 'Estados Unidos' 'Nigeria'
 'República Democrática del Congo' 'Senegal' 'Marruecos' 'Alemania'
 'Francia' 'Países Bajos' 'Reino Unido' 'Guatemala' 'El Salvador' 'Panamá'
 'República Dominicana' 'Venezuela' 'Colombia' 'Honduras' 'Brasil'
 'México' 'Uruguay' 'Argentina' 'Cuba' 'Perú' 'Nicaragua' 'Ecuador'
 'Angola' 'Sudán' 'Somalia' 'Costa de Marfil' 'Egipto' 'Italia' 'España'
 'Suecia' 'Austria' 'Canada' 'Madagascar' 'Argelia' 'Liberia' 'Zambia'
 'Níger' 'SudAfrica' 'Mozambique' 'Tanzania' 'Ruanda' 'Israel'
 'Nueva Zelanda' 'Bangladés' 'Tailandia' 'Irak' 'Arabia Saudí' 'Filipinas'
 'Kazajistán' 'Irán' 'Myanmar (Birmania)' 'Uzbekistán' 'Benín' 'Camerún'
 'Kenia' 'Togo' 'Ucrania' 'Polonia' 'Portugal' 'Rumania'
 'Trinidad y Tobago' 'Afganistán' 'Pakistán' 'Vietnam' 'Malasia'
 'Finlandia' 'Rusia' 'Irlanda' 'Noruega' 'Eslovaquia' 'Bélgica' 'Bolivia'
 'Chile' 'Jamaica' 'Yemen' 'Ghana' 'Guinea' 'Etiopía' 'Bulgaria'
 'Kirguistán' 'Georgia' 'Nepal' 'Emiratos Árabes Unidos' 'Camboya'
 'Uganda' 'Lesoto' 'Lituania' 'Suiza' 'Hungría' 'Dinamarca' 'Haití'
 'Bielorrusia' 'Croacia' 'Laos' 'Baréin' 'Macedonia' 'República Checa'
 'Sri Lanka' 'Zimbabue' 'Eritrea' 'Burkina Faso' 'Costa Rica' 'Libia'
 'Barbados' 'Tayikistán' 'Siria' 'Guadalupe' 'Papúa Nueva Guinea'
 'Azerbaiyán' 'Turkmenistán' 'Paraguay' 'Jordania' 'Hong Kong' 'Martinica'
 'Moldavia' 'Qatar' 'Mali' 'Albania' 'República del Congo'
 'Bosnia y Herzegovina' 'Omán' 'Túnez' 'Sierra Leona' 'Yibuti' 'Burundi'
 'Montenegro' 'Gabón' 'Sudán del Sur' 'Luxemburgo' 'Namibia' 'Mauritania'
 'Grecia' 'Suazilandia' 'Guyana' 'Guayana Francesa'
 'República Centroafricana' 'Taiwán' 'Estonia' 'Líbano' 'Chipre'
 'Guinea-Bissau' 'Surinam' 'Belice' 'Eslovenia' 'República de Gambia'
 'Botsuana' 'Armenia' 'Guinea Ecuatorial' 'Kuwait' 'Bután' 'Chad' 'Serbia'
 'Sáhara Occidental']

Order Region column unique values :  ['Southeast Asia' 'South Asia' 'Oceania' 'Eastern Asia' 'West Asia'
 'West of USA ' 'US Center ' 'West Africa' 'Central Africa' 'North Africa'
 'Western Europe' 'Northern Europe' 'Central America' 'Caribbean'
 'South America' 'East Africa' 'Southern Europe' 'East of USA' 'Canada'
 'Southern Africa' 'Central Asia' 'Eastern Europe' 'South of  USA ']

Order State column unique values :  ['Java Occidental' 'Rajastán' 'Queensland' ... 'Bistrita-Nasaud' 'Tottori'
 'Khorezm']

Product Name column unique values :  ['Smart watch ' 'Perfect Fitness Perfect Rip Deck'
 "Under Armour Girls' Toddler Spine Surge Runni"
 "Nike Men's Dri-FIT Victory Golf Polo"
 "Under Armour Men's Compression EV SL Slide"
 "Under Armour Women's Micro G Skulpt Running S"
 "Nike Men's Free 5.0+ Running Shoe"
 "Glove It Women's Mod Oval 3-Zip Carry All Gol"
 'Bridgestone e6 Straight Distance NFL San Dieg'
 "Columbia Men's PFG Anchor Tough T-Shirt" 'Titleist Pro V1x Golf Balls'
 'Bridgestone e6 Straight Distance NFL Tennesse'
 'Polar FT4 Heart Rate Monitor' 'ENO Atlas Hammock Straps'
 "adidas Men's F10 Messi TRX FG Soccer Cleat"
 "Brooks Women's Ghost 6 Running Shoe"
 "Nike Men's CJ Elite 2 TD Football Cleat"
 "Diamondback Women's Serene Classic Comfort Bi"
 'Industrial consumer electronics' 'Web Camera' 'Dell Laptop'
 'SOLE E25 Elliptical' 'Elevation Training Mask 2.0'
 "adidas Men's Germany Black Crest Away Tee"
 'Team Golf Pittsburgh Steelers Putter Grip'
 'Glove It Urban Brick Golf Towel' 'Team Golf Texas Longhorns Putter Grip'
 "Nike Men's Deutschland Weltmeister Winners Bl"
 'Team Golf St. Louis Cardinals Putter Grip' 'Summer dresses'
 'Porcelain crafts' "Men's gala suit"
 'Team Golf Tennessee Volunteers Putter Grip'
 'Team Golf San Francisco Giants Putter Grip'
 'Glove It Imperial Golf Towel' "Nike Men's Comfort 2 Slide"
 'Under Armour Hustle Storm Medium Duffle Bag'
 "Under Armour Kids' Mercenary Slide"
 "Under Armour Women's Ignite PIP VI Slide"
 "Nike Men's Free TR 5.0 TB Training Shoe"
 'adidas Youth Germany Black/Red Away Match Soc'
 "TYR Boys' Team Digi Jammer" "Glove It Women's Imperial Golf Glove"
 'Titleist Pro V1x High Numbers Golf Balls'
 'Bridgestone e6 Straight Distance NFL Carolina'
 "Under Armour Women's Ignite Slide"
 'Titleist Pro V1x High Numbers Personalized Go'
 'GoPro HERO3+ Black Edition Camera' 'Total Gym 1400' "Children's heaters"
 'Team Golf New England Patriots Putter Grip'
 "adidas Kids' F5 Messi FG Soccer Cleat" "Nike Women's Tempo Shorts"
 "Glove It Women's Mod Oval Golf Glove"
 'Titleist Pro V1 High Numbers Personalized Gol'
 "Under Armour Men's Tech II T-Shirt" 'Baby sweater'
 'Mio ALPHA Heart Rate Monitor/Sport Watch'
 'Field & Stream Sportsman 16 Gun Fire Safe' 'Sports Books '
 "Diamondback Boys' Insight 24 Performance Hybr"
 'Polar Loop Activity Tracker' 'Garmin Forerunner 910XT GPS Watch' 'DVDs '
 'CDs of rock' "Nike Kids' Grade School KD VI Basketball Shoe"
 "Nike Women's Free 5.0 TR FIT PRT 4 Training S"
 "Hirzl Women's Soffft Flex Golf Glove"
 "The North Face Women's Recon Backpack" 'Lawn mower'
 'Nike Dri-FIT Crew Sock 6 Pack' "Nike Women's Legend V-Neck T-Shirt"
 'Garmin Approach S4 Golf GPS Watch' 'insta-bed Neverflat Air Mattress'
 "Nike Men's Kobe IX Elite Low Basketball Shoe" 'Adult dog supplies'
 'First aid kit' 'Garmin Approach S3 Golf GPS Watch' 'Rock music'
 'Fighting video games' 'Fitbit The One Wireless Activity & Sleep Trac'
 'Stiga Master Series ST3100 Competition Indoor'
 "Diamondback Girls' Clarity 24 Hybrid Bike 201"
 'adidas Brazuca 2014 Official Match Ball' 'GolfBuddy VT3 GPS Watch'
 'Bushnell Pro X7 Jolt Slope Rangefinder'
 'Yakima DoubleDown Ace Hitch Mount 4-Bike Rack'
 "Nike Men's Fingertrap Max Training Shoe"
 'Bowflex SelectTech 1090 Dumbbells' 'SOLE E35 Elliptical'
 "Hirzl Women's Hybrid Golf Glove" "Hirzl Men's Hybrid Golf Glove"
 'TaylorMade 2014 Purelite Stand Bag' 'Bag Boy Beverage Holder'
 'Bag Boy M330 Push Cart' 'Clicgear 8.0 Shoe Brush'
 'Titleist Small Wheeled Travel Cover' 'Clicgear Rovic Cooler Bag'
 'Titleist Club Glove Travel Cover' 'Ogio Race Golf Shoes'
 "LIJA Women's Argyle Golf Polo"
 "LIJA Women's Eyelet Sleeveless Golf Polo"
 "LIJA Women's Button Golf Dress"
 "LIJA Women's Mid-Length Panel Golf Shorts"
 "TaylorMade Women's RBZ SL Rescue"
 "Cleveland Golf Women's 588 RTX CB Satin Chrom"
 "Top Flite Women's 2014 XL Hybrid" 'MDGolf Pittsburgh Penguins Putter'
 'TaylorMade White Smoke IN-12 Putter'
 'Cleveland Golf Collegiate My Custom Wedge 588'
 "Merrell Men's All Out Flash Trail Running Sho"
 "Merrell Women's Grassbow Sport Waterproof Hik"
 "Merrell Women's Siren Mid Waterproof Hiking B"
 "Merrell Women's Grassbow Sport Hiking Shoe" 'Toys '
 'Pelican Sunstream 100 Kayak' 'Pelican Maverick 100X Kayak'
 "O'Brien Men's Neoprene Life Vest"]

In [215]:
#removing the leading and trailing spaces in the text from department name column
data['Department Name'] = (data['Department Name'].str.strip())

In [216]:
data['Department Name'].unique()

array(['Fitness', 'Apparel', 'Golf', 'Footwear', 'Outdoors', 'Fan Shop',
       'Technology', 'Book Shop', 'Discs Shop', 'Pet Shop',
       'Health and Beauty'], dtype=object)

In [217]:
# Check for leading/trailing whitespace in all categorical columns

categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    whitespace_values = data[col].dropna().loc[
        data[col].dropna().str.strip() != data[col].dropna()
    ]
    
    if len(whitespace_values) > 0:
        print(f"\n{col}")
        print(whitespace_values.unique()[:20])

Category Name
['Cameras ' 'Baby ' 'Books ' 'CDs ']

Customer Street
['2668 Velvet Row ' '567 Fallen Pines ' '5763 Green Crossing '
 '8297 Golden Green ' '6370 Emerald Row ' '4896 Honey Wood '
 '3710 Little Nook ' '7320 Wishing Rise Mall ' '3614 Misty Mall '
 '5274 Hidden Mall ' '7969 Thunder Butterfly Mall ' '7868 Iron Fawn Mall '
 '4320 Iron Highlands ' '6724 High Chase ' '3278 Cotton Crest '
 '797 Heather Thicket ' '6997 Middle Acres ' '1777 High Alley '
 '2407 Bright Blossom Mall ' '6332 Round Range ']

Order Region
['West of USA ' 'US Center ' 'South of  USA ']

Product Name
['Smart watch ' 'Sports Books ' 'DVDs ' 'Toys ']

In [218]:
#removing leading and trailiing spaces from the columns which contains spaces
categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    data[col] = data[col].str.strip()

In [219]:
#find the customer state column which contain these values ('95758', '91732') and understand with other related columns
data[data['Customer State'].isin(['95758', '91732'])][
    ['Customer City', 'Customer State', 'Customer Country', 'Customer Zipcode']
]

      Customer City Customer State Customer Country  Customer Zipcode
35704            CA          95758          EE. UU.               NaN
46440            CA          95758          EE. UU.               NaN
82511            CA          91732          EE. UU.               NaN

In [220]:
# Fix misplaced ZIP codes in Customer State

mask = data['Customer State'].isin(['95758', '91732'])

data.loc[mask, 'Customer Zipcode'] = data.loc[mask, 'Customer State']
data.loc[mask, 'Customer State'] = 'CA'

C:\Users\Admin\AppData\Local\Temp\ipykernel_10852\3862621850.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['95758' '95758' '91732']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data.loc[mask, 'Customer Zipcode'] = data.loc[mask, 'Customer State']

In [221]:
#check missing values in each columns
missing = data.isnull().sum()

missing[missing > 0]

Series([], dtype: int64)

In [222]:
numerical_col = data.select_dtypes(include='number').columns

print(numerical_col.to_list())

['Days for shipment (scheduled)', 'Sales per customer', 'Late_delivery_risk', 'Category Id', 'Customer Id', 'Department Id', 'Latitude', 'Longitude', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Product Card Id', 'Product Category Id', 'Product Price']

In [223]:
#find the columns which contains negative values
negative_counts = (data[numerical_col] < 0).sum()

negative_counts[negative_counts > 0]

Latitude          9
Longitude    180414
dtype: int64

In [224]:
#understand lattitue and longitude columns
data[['Latitude', 'Longitude']].describe()

            Latitude      Longitude
count  180519.000000  180519.000000
mean       29.719955     -84.915675
std         9.813646      21.433241
min       -33.937553    -158.025986
25%        18.265432     -98.446312
50%        33.144863     -76.847908
75%        39.279617     -66.370583
max        48.781933     115.263077

In [225]:
#find the columns which contain zero value
zero_counts = (data[numerical_col]==0).sum()

zero_counts[zero_counts>0]

Days for shipment (scheduled)     9737
Late_delivery_risk               81542
Order Item Discount              10028
Order Item Discount Rate         10028
dtype: int64

In [226]:
#check number of unique values in days for shipment 
data['Days for shipment (scheduled)'].value_counts().sort_index()

Days for shipment (scheduled)
0      9737
1     27814
2     35216
4    107752
Name: count, dtype: int64

In [227]:
#Is 0 days shipment (scheduled) is related to same day shipping mode
data[data['Days for shipment (scheduled)'] == 0]['Shipping Mode'].value_counts()

Shipping Mode
Same Day    9737
Name: count, dtype: int64

In [228]:
#understanding order item discount and order item discount rate
data[['Order Item Discount', 'Order Item Discount Rate']].describe()

       Order Item Discount  Order Item Discount Rate
count        180519.000000             180519.000000
mean             20.664741                  0.101668
std              21.800901                  0.070415
min               0.000000                  0.000000
25%               5.400000                  0.040000
50%              14.000000                  0.100000
75%              29.990000                  0.160000
max             500.000000                  0.250000

In [229]:
#checking that is 500 value in order item discount is legitimate or suspecious
data[data['Order Item Discount'] == 500][
    ['Order Item Discount',
     'Order Item Discount Rate',
     'Order Item Product Price',
     'Order Item Quantity',
     'Sales',
     'Order Item Total',
     'Product Name']
]

#outcome -> legitimate

,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Quantity,Sales,Order Item Total,Product Name
12606,500.0,0.25,1999.98999,1,1999.98999,1499.98999,SOLE E35 Elliptical

In [230]:
#understanding various columns which listed below
data[
    ['Order Item Product Price',
     'Product Price',
     'Sales',
     'Order Item Total',
     'Sales per customer']
].describe()

,Order Item Product Price,Product Price,Sales,Order Item Total,Sales per customer
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,141.232550,141.232550,203.772096,183.107609,183.107609
std,139.732492,139.732492,132.273077,120.043670,120.043670
min,9.990000,9.990000,9.990000,7.490000,7.490000
25%,50.000000,50.000000,119.980003,104.379997,104.379997
50%,59.990002,59.990002,199.919998,163.990005,163.990005
75%,199.990005,199.990005,299.950012,247.399994,247.399994
max,1999.989990,1999.989990,1999.989990,1939.989990,1939.989990

In [231]:
data['Order Item Quantity'].describe()

count    180519.000000
mean          2.127638
std           1.453451
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max           5.000000
Name: Order Item Quantity, dtype: float64

In [232]:
data['Late_delivery_risk'].value_counts().sort_index()

Late_delivery_risk
0    81542
1    98977
Name: count, dtype: int64

In [233]:
#Is product price and order item product price are redundant?
(data['Product Price'] == data['Order Item Product Price']).all()


#outcome -> yes

np.True_

In [234]:
#Is sales per customer and order item total are redundant?
(data['Sales per customer'] == data['Order Item Total']).all()

#outcome -> yes

np.True_

In [235]:
#Is category id and product category id are redundant?
(data['Category Id'] == data['Product Category Id']).all()

#outcome -> yes

np.True_

In [236]:
#Is product card id and order item cardprod id are redundant?
(data['Product Card Id'] == data['Order Item Cardprod Id']).all()

np.True_

In [237]:
#dropping redundant columns
data.drop(columns=[
    'Order Item Product Price',
    'Sales per customer',
    'Product Category Id',
    'Order Item Cardprod Id'
], inplace=True)

In [238]:
data.shape

(180519, 32)

In [239]:
#missing value check
missing = data.isnull().sum()
missing[missing > 0]

Series([], dtype: int64)

In [240]:
#checking duplicate rows
print(data.duplicated().sum())

0

In [241]:
#checking data type
data.dtypes

Type                                     object
Days for shipment (scheduled)             int64
Late_delivery_risk                        int64
Category Id                               int64
Category Name                            object
Customer City                            object
Customer Country                         object
Customer Id                               int64
Customer Segment                         object
Customer State                           object
Customer Street                          object
Customer Zipcode                         object
Department Id                             int64
Department Name                          object
Latitude                                float64
Longitude                               float64
Market                                   object
Order City                               object
Order Country                            object
order date (DateOrders)          datetime64[ns]
Order Item Discount                     float64
Order Item Discount Rate                float64
Order Item Id                             int64
Order Item Quantity                       int64
Sales                                   float64
Order Item Total                        float64
Order Region                             object
Order State                              object
Product Card Id                           int64
Product Name                             object
Product Price                           float64
Shipping Mode                            object
dtype: object

In [242]:
#current columns
data.columns.tolist()

['Type',
 'Days for shipment (scheduled)',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Id',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'order date (DateOrders)',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Region',
 'Order State',
 'Product Card Id',
 'Product Name',
 'Product Price',
 'Shipping Mode']

In [243]:
categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    if col != 'Customer Zipcode':
        multiple_space_count = data[col].str.contains(
            r'\s{2,}',
            regex=True,
            na=False
        ).sum()

        if multiple_space_count > 0:
            print(f"{col}: {multiple_space_count} values with multiple spaces")

Category Name: 68 values with multiple spaces
Customer Street: 1219 values with multiple spaces
Order Region: 4045 values with multiple spaces

In [244]:
categorical_cols = data.select_dtypes(include='object').columns

for col in categorical_cols:
    if col != 'Customer Zipcode':
        data[col] = (
            data[col]
            .str.replace(r'\s+', ' ', regex=True)
            .str.strip()
        )

In [245]:
data.shape

(180519, 32)

In [246]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 32 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipment (scheduled)  180519 non-null  int64
 2   Late_delivery_risk             180519 non-null  int64
 3   Category Id                    180519 non-null  int64
 4   Category Name                  180519 non-null  object
 5   Customer City                  180519 non-null  object
 6   Customer Country               180519 non-null  object
 7   Customer Id                    180519 non-null  int64
 8   Customer Segment               180519 non-null  object
 9   Customer State                 180519 non-null  object
 10  Customer Street                180519 non-null  object
 11  Customer Zipcode               180519 non-null  object
 12  Department Id                  180519 non-null  int64
 13  Department Name                180519 non-null  object
 14  Latitude                       180519 non-null  float64
 15  Longitude                      180519 non-null  float64
 16  Market                         180519 non-null  object
 17  Order City                     180519 non-null  object
 18  Order Country                  180519 non-null  object
 19  order date (DateOrders)        180519 non-null  datetime64[ns]
 20  Order Item Discount            180519 non-null  float64
 21  Order Item Discount Rate       180519 non-null  float64
 22  Order Item Id                  180519 non-null  int64
 23  Order Item Quantity            180519 non-null  int64
 24  Sales                          180519 non-null  float64
 25  Order Item Total               180519 non-null  float64
 26  Order Region                   180519 non-null  object
 27  Order State                    180519 non-null  object
 28  Product Card Id                180519 non-null  int64
 29  Product Name                   180519 non-null  object
 30  Product Price                  180519 non-null  float64
 31  Shipping Mode                  180519 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(8), object(16)
memory usage: 44.1+ MB

In [247]:
data.isnull().sum()[data.isnull().sum() > 0]

Series([], dtype: int64)

In [248]:
#save the final processed data for further processing
data.to_csv("D:/projects/supply chain project/datasets/processed/DataCoSupplyChain_cleaned.csv")